Repository icure/icure-typescript-sdk, pull requests merged in 2022-11, with the labels that each got.

#20 Renamed deleteItem to removeItem
  icc-x-api/icc-crypto-x-api.ts
  icc-x-api/storage/KeyStorageImpl.ts
  icc-x-api/storage/LocalStorageImpl.ts
  icc-x-api/storage/StorageFacade.ts
  test/icc-x-api/storage/storage.ts
Labels: bug

#24 Updated full crypto test with new test stack
  test/icc-x-api/crypto/full-crypto-test.ts
  test/utils/test-utils-decorators.ts
  test/utils/test_utils.ts
Labels: enhancement

#28 V5 - Cherry pciekd changes from v6
  icc-api/api/IccAuthApi.ts
  icc-x-api/index.ts
  test/icc-x-api/auth/jwt-concurrency-test.ts
  test/icc-x-api/crypto/full-crypto-test.ts
  test/icc-x-api/icc-accesslog-x-api.ts
  test/icc-x-api/icc-auth-api.ts
  test/icc-x-api/icc-time-table-x-api.ts
Labels: bug

#26 Automation of release management
  .github/release.yml
  .github/workflows/publish.yml
Labels: documentation, ignore-for-release
