Repository icure/icure-typescript-sdk, pull requests merged in 2022-12, with the labels that each got.

#31 Added authentication header to token endpoint
  icc-api/api/IccAuthApi.ts
  package.json
  test/icc-x-api/crypto/full-crypto-test.ts
  test/utils/test_utils.ts
  yarn.lock
Labels: bug, SemVer.Patch

#32 Solved bug on JWT duration
  icc-x-api/auth/JwtAuthService.ts
  test/icc-x-api/auth/jwt-concurrency-test.ts
Labels: bug

#33 Cherry picked changes from v5
  icc-api/api/IccAuthApi.ts
  icc-x-api/auth/JwtAuthService.ts
  package.json
  test/icc-x-api/icc-user-x-api-test.ts
  test/utils/test_utils.ts
Labels: bug

#37 Add filter by name on Healthcare parties
  icc-x-api/filters/HealthcarePartyByNameFilter.ts
  icc-x-api/filters/filters.ts
Labels: enhancement, SemVer.Patch

#38 Release 6.0.5
  icc-api/api/IccAuthApi.ts
  icc-api/model/ModelHelper.ts
  icc-x-api/auth/JwtAuthService.ts
  icc-x-api/filters/HealthcarePartyByNameFilter.ts
  icc-x-api/filters/filters.ts
  icc-x-api/icc-crypto-x-api.ts
  package.json
  test/icc-x-api/icc-user-x-api-test.ts
  test/utils/test_utils.ts
Labels: SemVer.Patch
