Repository icure/icure-typescript-sdk, pull requests merged in 2023-02, with the labels that each got.

#50 Release/6.3.0
  icc-x-api/icc-crypto-x-api.ts
  icc-x-api/icc-patient-x-api.ts
  package.json
  test-scripts/cleanup.ts
  test/icc-x-api/crypto/concurrency.ts
  test/icc-x-api/crypto/cryptoTest.ts
  test/icc-x-api/crypto/full-crypto-test.ts
  test/icc-x-api/crypto/shamir.ts
  test/icc-x-api/crypto/share-to-newly-created-patient-from-hcp.ts
Labels: SemVer.Minor

#52 Fixed the condition that caused skipPatients to be ignored when set to false
  icc-api/api/IccUserApi.ts
Labels: bug

#53 Fixed the condition that caused skipPatients to be ignored when set to false
  icc-api/api/IccUserApi.ts
Labels: bug

#54 Fixed the condition that caused skipPatients to be ignored when set to false (#52)
  icc-api/api/IccUserApi.ts
Labels: SemVer.Patch
