Repository icure/icure-typescript-sdk, pull requests merged in 2023-01, with the labels that each got.

#39 Patch release management
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: ignore-for-release

#40 Add missing apis
  .github/workflows/build.yml
  icc-x-api/index.ts
  yarn.lock
Labels: enhancement

#42 Release/6.1.0
  icc-x-api/index.ts
  icc-x-api/utils/formatting-util.ts
  icc-x-api/utils/insurability-util.ts
  yarn.lock
Labels: SemVer.Minor

#46 Release/6.2.1
  icc-api/model/Document.ts
  icc-api/model/Measure.ts
  icc-api/model/Medication.ts
  icc-api/model/Patient.ts
  icc-api/model/PermissionItem.ts
  icc-api/model/TimeTableItem.ts
Labels: SemVer.Patch
